<?php

namespace App\DataFixtures;

use App\Entity\Book;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

/**
 * LA PILE À LIRE - DATABASE & STATISTICS
 * ======================================
 *
 * Responsabilités:
 * - BOOKS_DATABASE: catalogue complet de tous les livres (statique, lu une seule fois)
 * - GENRES_LIST: liste des genres disponibles pour les filtres
 * - getStatistics(): calcule les stats affichées sur la page (total, moyennes, counts)
 *
 * Aucune manipulation du DOM ici.
 * Les données ne sont jamais modifiées en cours d'exécution.
 */

// ========== CATALOGUE DES LIVRES ==========

/**
 * BOOKS_DATABASE: Tableau statique de tous les livres disponibles.
 *
 * Structure commune à tous les livres:
 * - id (number): identifiant unique persistant (même si le titre change)
 * - title (string): nom affiché sur les cartes et modals
 * - author (string): auteur affiché sous le titre
 * - format (string): "papier" | "ebook" | "audio"
 * - pages (number | null): nombre de pages (null pour audios)
 * - duration (string, optionnel): "Xh Ym" uniquement pour format "audio"
 * - genres (string[]): tableau de slugs (ex: ["fantasy", "adventure"])
 * - summary (string): résumé affiché dans la modal de détail
 * - cover_color (string): classe CSS pour la couleur de couverture.
 *     Doit correspondre à une classe définie dans app.css (ex: "genre-fantasy").
 *     NE PAS générer depuis le slug — utiliser la table de correspondance
 *     GENRE_COLOR_MAP ci-dessous pour s'assurer que la classe existe bien.
 * - series (string, optionnel): nom de la série (ex: "Dungeon Crawler Carl")
 *     Si null, le livre est considéré comme standalone.
 * - book_number (number, optionnel): numéro du tome dans la série (ex: 1, 2, 3)
 *     Si null, le livre est considéré comme standalone.
 * - language (string): "fr" | "en" (défaut: "fr")
 *     Utilisé dans la recherche textuelle pour retrouver les livres par langue */

class BookFixtures extends Fixture
{
  public function load(ObjectManager $manager): void
  {
    $books = $this->getBooksData();

    foreach ($books as $data) {
      $book = new Book();
      $book->setTitle($data['title']);
      $book->setAuthor($data['author']);
      $book->setFormat($data['format']);
      $book->setPages($data['pages'] ?? null);
      $book->setDuration($data['duration'] ?? null);
      $book->setGenres($data['genres']);
      $book->setSummary($data['summary']);
      $book->setCoverColor($data['cover_color']);
      $book->setSeries($data['series'] ?? null);
      $book->setBookNumber($data['book_number'] ?? null);
      $book->setLanguage($data['language'] ?? 'fr');
      $manager->persist($book);
    }

    $manager->flush();
  }

  private function getBooksData(): array
  {
    // Copiez ici le contenu de BOOKS_DATABASE depuis votre data.js,
    // converti en tableau PHP. Exemple pour les premiers livres :

    return [
      [
        'id'          => 1,
        'title'       => 'Dungeon Crawler Carl',
        'author'      => 'Matt Dinniman',
        'format'      => 'ebook',
        'pages'       => 528,
        'duration'    => null,
        'genres'      => ['science-fiction', 'adventure', 'humour'],
        'cover_color' => 'genre-sf',
        'series'      => 'Dungeon Crawler Carl',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "It's the most-watched game show in the galaxy! In a flash, every human-erected construction on Earth--from Buckingham Palace to the tiniest of sheds to all the trucks and cars--collapses in a heap, sinking into the ground. The buildings and all the people inside, they've all been atomized and transformed into the dungeon: an 18-level labyrinth filled with traps, monsters, and loot. A dungeon so enormous, it circles the entire globe. Only a few dare venture inside. But once you're in, you can't get out. And what's worse, each level has a time limit. You have but days to find a staircase to the next level down, or it's game over. In this game, it's not about your strength or your dexterity. It's about your views and your followers. It's about building an audience and killing those goblins with style. You can't just survive here. You gotta survive big.",
      ],
      [
        'id'          => 2,
        'title'       => "L'Ogive du jugement dernier",
        'author'      => 'Matt Dinniman',
        'format'      => 'ebook',
        'pages'       => 407,
        'duration'    => null,
        'genres'      => ['science-fiction', 'adventure', 'humour'],
        'cover_color' => 'genre-sf',
        'series'      => 'Dungeon Crawler Carl',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "Que devient le duo de choc le plus suivi de l'univers ? Arrivés au niveau 3, Carl et Donut, auxquels s'est joint le jeune Mongo, sont à la croisée des chemins. Ils doivent sélectionner une race et une classe : perspective aussi excitante qu'effrayante, qui les changera peut-être pour toujours... Et ce n'est pas tout. Surprise : la vaste métropole où se déroule cette nouvelle partie de l'aventure n'est en fait que le premier palier d'un réseau de six niveaux urbains interconnectés, où les attendent des défis plus périlleux les uns que les autres. Le risque est partout, et gagner de l'expérience n'a jamais été aussi crucial. Mais les nouvelles quêtes proposées à Carl et Donut viennent perturber le cours du jeu...",
      ],
      [
        'id'          => 3,
        'title'       => 'Le Livre de recettes de l\'Anarchiste',
        'author'      => 'Matt Dinniman',
        'format'      => 'ebook',
        'pages'       => 581,
        'duration'    => null,
        'genres'      => ['science-fiction', 'adventure', 'humour'],
        'cover_color' => 'genre-sf',
        'series'      => 'Dungeon Crawler Carl',
        'book_number' => 3,
        'language'    => 'fr',
        'summary'     => "Les efforts de Carl et Donut ont payé : non seulement ils ont survécu aux trois premiers niveaux, mais leur équipe est l'une des plus célèbres et des plus appréciées du jeu ! Cette popularité qui les a propulsés dans le prestigieux top 10 n'est pas sans revers, une prime en pièces d'or est désormais promise à quiconque les éliminera. Pour venir à bout du niveau 4, véritable labyrinthe ferroviaire, les crawlers vont devoir unir leurs forces, mais à qui se fier quand votre tête est mise à prix ? Cerise sur le gâteau : le soutien des mécènes présage de nouveaux conflits tant à l'intérieur qu'à l'extérieur du donjon. Carl fait alors l'acquisition d'un objet en apparence insignifiant qui pourrait pourtant faire basculer le cours de la saison... et même de l'univers.",
      ],
      [
        'id'          => 4,
        'title'       => 'Le Portail des dieux infernaux',
        'author'      => 'Matt Dinniman',
        'format'      => 'ebook',
        'pages'       => 643,
        'duration'    => null,
        'genres'      => ['science-fiction', 'adventure', 'humour'],
        'cover_color' => 'genre-sf',
        'series'      => 'Dungeon Crawler Carl',
        'book_number' => 4,
        'language'    => 'fr',
        'summary'     => "Projetés dans l'une des 1 172 bulles qui composent le niveau 5, Carl, Donut et Katia n'ont que deux semaines pour conquérir les quatre bastions qu'elle contient et, ainsi, débloquer l'accès aux escaliers. Comme si cela ne suffisait pas, la plupart des crawlers avec lesquels ils sont forcés de collaborer sont soit des boulets incompétents, soit de niveaux trop faibles pour véritablement les aider. Heureusement, Carl bénéficie toujours d'un atout de taille, bien caché dans son inventaire. Il doit cependant rester sur ses gardes : les maîtres du jeu – ainsi que Loita, la nouvelle agente de l'équipe – l'ont à l'œil, tolérant de moins en moins ses provocations. Au moindre soupçon, le Livre lui sera retiré ; au moindre écart, c'est l'accélération assurée. Rien, pourtant, ne le fera dévier de sa nouvelle résolution. Ils ne le briseront pas. Jamais. C'est lui qui les brisera. Tous.",
      ],
      [
        'id'          => 5,
        'title'       => 'Mortimer',
        'author'      => 'Terry Pratchett',
        'format'      => 'papier',
        'pages'       => 236,
        'duration'    => null,
        'genres'      => ['fantasy', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => 'Les annales du Disque-monde',
        'book_number' => 3,
        'language'    => 'fr',
        'summary'     => "Un destin hors du commun attend Mortimer. Car à la foire à l'embauche, LA MORT l'emporte sur son cheval Bigadin. Il faut dire que LA MORT a décidé de faire la vie ; et l'assistance d'un commis dans son labeur quotidien lui permettrait des loisirs. Mais... Est-ce bien raisonnable ?",
      ],
      [
        'id'          => 6,
        'title'       => 'Le Faucheur',
        'author'      => 'Terry Pratchett',
        'format'      => 'papier',
        'pages'       => 448,
        'duration'    => null,
        'genres'      => ['fantasy', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => 'Les annales du Disque-monde',
        'book_number' => 11,
        'language'    => 'fr',
        'summary'     => "Du pain sur les quatre planches pour le défunt Raymond Soulier, activiste résolu : fantômes, vampires, zombis, banshees, croque-mitaines... les morts vivants se multiplient. Car une catastrophe frappe le Disque-monde : la Mort est porté disparu (oui, la mort est mâle, un mâle nécessaire). Il s'ensuit un chaos général tel qu'en provoque toujours la déficience d'un service public essentiel. Tandis que dans les champs d'une ferme lointaine, un étrange et squelettique ouvrier agricole manie la faux avec une rare dextérité. La moisson n'attend pas...",
      ],
      [
        'id'          => 7,
        'title'       => 'Accros du roc',
        'author'      => 'Terry Pratchett',
        'format'      => 'papier',
        'pages'       => 412,
        'duration'    => null,
        'genres'      => ['fantasy', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => 'Les annales du Disque-monde',
        'book_number' => 16,
        'language'    => 'fr',
        'summary'     => "Aux enfants ordinaires on offre des xylophones. Suzanne, elle, n'avait qu'à demander à son grand-père d'ôter son gilet... Oui, elle avait la Mort dans sa famille. Et il est difficile de grandir normalement quand votre aïeul monte un cheval blanc et manie la faux, surtout quand vous devez reprendre l'affaire familiale pour cause de vacance et que tout le monde vous tient pour la « fée des dents ». Bien plus difficile encore quand il s'agit d'affronter la nouvelle musique – une vraie drogue – qui a fait irruption dans le Disque-monde. Elle n'obéit à aucune loi. Elle transforme les gens. On l'appelle la « musique de rocs ». Elle est rythmée, dansante, mais... Elle est vivante. Et elle ne s'arrête pas.",
      ],
      [
        'id'          => 8,
        'title'       => 'Procrastination',
        'author'      => 'Terry Pratchett',
        'format'      => 'papier',
        'pages'       => 414,
        'duration'    => null,
        'genres'      => ['fantasy', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => 'Les annales du Disque-monde',
        'book_number' => 19,
        'language'    => 'fr',
        'summary'     => "Le temps est une ressource qu'il faut gérer, chacun le sait. Sur le Disque-monde, c'est le boulot des moines de l'Histoire, qui l'emmagasinent, le prélèvent où on le gaspille (par exemple sous la mer : de combien de temps a besoin une morue ?) et le redistribuent à de gros consommateurs comme les villes où l'on en manque toujours. Mais la fabrication de la première horloge du monde vraiment précise donne le départ d'une course contre... disons la montre pour Lou-tsé et son apprenti Lobsang. Parce qu'elle va arrêter le temps. Et ce ne sera que le début des ennuis. Procrastination (voir dictionnaire) s'est assuré la participation de héros et de canailles, de yétis, d'artistes martiaux et de Ronnie, le cinquième cavalier de l'Apocalypse (qui a quitté le groupe avant qu'il devienne célèbre).",
      ],
      [
        'id'          => 9,
        'title'       => 'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch',
        'author'      => 'Terry Pratchett, Neil Gaiman, narrated by a full cast',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '12h14m',
        'genres'      => ['fantasy', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "According to The Nice and Accurate Prophecies of Agnes Nutter, Witch (the world's only completely accurate book of prophecies, written in 1655, before she exploded), the world will end on a Saturday. Next Saturday, in fact. Just before dinner. So the armies of Good and Evil are amassing, Atlantis is rising, frogs are falling, tempers are flaring. Everything appears to be going according to Divine Plan. Except a somewhat fussy angel and a fast-living demon—both of whom have lived amongst Earth's mortals since The Beginning and have grown rather fond of the lifestyle—are not actually looking forward to the coming Rapture. And someone seems to have misplaced the Antichrist . . . ",
      ],
      [
        'id'          => 10,
        'title'       => 'Lore Olympus',
        'author'      => 'Rachel Smythe',
        'format'      => 'papier',
        'pages'       => 384,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'romance', 'fantasy'],
        'cover_color' => 'genre-manga',
        'series'      => 'Lore Olympus',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "Scandalous gossip, wild parties, and forbidden love—witness what the gods do after dark in this stylish and contemporary reimagining of one of the best-known stories in Greek mythology.",
      ],
      [
        'id'          => 11,
        'title'       => 'Harleen',
        'author'      => 'Stjepan Sejic',
        'format'      => 'papier',
        'pages'       => 208,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'thriller', 'drama'],
        'cover_color' => 'genre-manga',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Dr. Harleen Quinzel has a theory: mental illness is a survival mechanism. As she seeks to help the broken souls of Gotham City piece together their sanity she will become the one thing she fears the most: one of them. A bold new retelling of the tragic origin of Harley Quinn told through the eyes of the only person who knows her better than anyone: Harleen.",
      ],
      [
        'id'          => 12,
        'title'       => 'En avant, tête de thon !',
        'author'      => 'Bill Watterson',
        'format'      => 'papier',
        'pages'       => 63,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'humour', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Calvin & Hobbes',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "L'enfance est pleine de désillusions et pleine d'inventions aussi. Heureusement Calvin, petit garçon de 6 ans, un peu turbulent, déborde d'imagination. Aidé de son fidèle tigre en peluche et compagnon Hobbes, il sait rendre la vie piquante et drôle. Tout le monde y passe : les parents, les filles, la maîtresse d'école. Mais la principale activité de ce tendre Calvin est d'animer le club le D.E.F.I. (Dehors énormes filles informes), dont Calvin et Hobbes sont seuls membres actifs, et ils se déchaînent sur la pauvre Susie Derkins.",
      ],
      [
        'id'          => 13,
        'title'       => 'On est fait comme des rats !',
        'author'      => 'Bill Watterson',
        'format'      => 'papier',
        'pages'       => 63,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'humour', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Calvin & Hobbes',
        'book_number' => 3,
        'language'    => 'fr',
        'summary'     => "L'enfance est pleine de désillusions et pleine d'inventions aussi. Heureusement Calvin, petit garçon de 6 ans, un peu turbulent, déborde d'imagination. Aidé de son fidèle tigre en peluche et compagnon Hobbes, il sait rendre la vie piquante et drôle. Tout le monde y passe : les parents, les filles, la maîtresse d'école. Mais la principale activité de ce tendre Calvin est d'animer le club le D.E.F.I. (Dehors énormes filles informes), dont Calvin et Hobbes sont seuls membres actifs, et ils se déchaînent sur la pauvre Susie Derkins.",
      ],
      [
        'id'          => 14,
        'title'       => 'Elle est pas belle, la vie ?',
        'author'      => 'Bill Watterson',
        'format'      => 'papier',
        'pages'       => 63,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'humour', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Calvin & Hobbes',
        'book_number' => 8,
        'language'    => 'fr',
        'summary'     => "L'enfance est pleine de désillusions et pleine d'inventions aussi. Heureusement Calvin, petit garçon de 6 ans, un peu turbulent, déborde d'imagination. Aidé de son fidèle tigre en peluche et compagnon Hobbes, il sait rendre la vie piquante et drôle. Tout le monde y passe : les parents, les filles, la maîtresse d'école. Mais la principale activité de ce tendre Calvin est d'animer le club le D.E.F.I. (Dehors énormes filles informes), dont Calvin et Hobbes sont seuls membres actifs, et ils se déchaînent sur la pauvre Susie Derkins.",
      ],
      [
        'id'          => 15,
        'title'       => 'Sherlock Holmes n\'a peur de rien',
        'author'      => 'Pierre Veys, Nicolas Barral (Dessin)',
        'format'      => 'papier',
        'pages'       => 47,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'humour', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Baker Street',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "Saviez-vous que Watson doit une grande partie de sa popularité à une méduse ? Que Holmes pratique parfois le cambriolage ? Et seriez-vous capable de trouver un rapport entre un diable en boîte, un haltère, un réveil-matin, un cactus et une masse d'armes ? Non ? Eh bien plongez-vous dans les carnets secrets du Dr Watson, miraculeusement exhumés par deux froggies... ",
      ],
      [
        'id'          => 16,
        'title'       => 'Sherlock Holmes et le club des sports dangereux',
        'author'      => 'Pierre Veys, Nicolas Barral (Dessin)',
        'format'      => 'papier',
        'pages'       => 47,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'humour', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Baker Street',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "Londres, l'été, les doks de Limehouse. Des choses horribles et autres disparitions mystérieuses ont lieu. Holmes et Watson, entraînés dans un entrepôt par l'inspecteur Lestrade, à la recherche de renseignements sur « le profanateur » (appelé ainsi parce qu'il dessine des moustaches sur les portraits officiels de la reine…), échappent de justesse à un attentat à la bière. L'enquête qui les attend n'est pas des plus aisée : un type décédé chez lui de mort naturelle dans son lit, portes fermées… et quelqu'un est persuadé que c'est un meurtre… Ils se rendent donc au club des sports dangereux, dont faisaient partie la victime.",
      ],
      [
        'id'          => 17,
        'title'       => 'Monsieur Noir 1',
        'author'      => 'Dufaux, Griffo (Dessin)',
        'format'      => 'papier',
        'pages'       => 63,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'supernatural'],
        'cover_color' => 'genre-manga',
        'series'      => 'Monsieur Noir',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "L'Angleterre, au siècle dernier. Un château : Blacktales. Tous les sept ans, son propriétaire, l'inquiétant Monsieur Noir, vient y signer un nouveau bail avec son locataire. À Blacktales, deux clans, irréductiblement opposés, se livrent une lutte féroce et sournoise pour la possession d'une plume : elle seule permet d'apposer sur le contrat de location la signature qui donne le pouvoir absolu. C'est dans un climat d'effervescence que débarque Fanny, récemment orpheline : la plume, égarée depuis deux ans, a été localisée. Elle se retrouve entre les mains de deux êtres dont l'impitoyable sadisme terrorise tous les habitants du lieu...",
      ],
      [
        'id'          => 18,
        'title'       => 'Monsieur Noir 2',
        'author'      => 'Dufaux, Griffo (Dessin)',
        'format'      => 'papier',
        'pages'       => 68,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'supernatural'],
        'cover_color' => 'genre-manga',
        'series'      => 'Monsieur Noir',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "La vie à Blacktales poursuit son cours, répondant à un rituel totalement absurde et pourtant inévitable et Fanny, la petite orpheline fraîchement arrivée, se plie tant bien que mal aux usages de la maisonnée. Alors qu'enfin, la cloche du matin vient de sonner, un rassemblement inhabituel a lieu dans la salle des cartes auquel la jeune fille est conviée. En effet, durant la nuit précédente, un cri spécifique a été entendu stipulant de fait que Pavane, qui avait pourtant disparu, est revenue. Qui est cette Pavane et pourquoi tant d'émoi autour d'elle ? Serait-elle en possession de la fameuse plume que tout le monde cherche pour devenir le prochain locataire de Blacktales ? Et pourquoi Lord Charleston a disparu ?",
      ],
      [
        'id'          => 19,
        'title'       => 'Hide: The Graphic Novel',
        'author'      => 'Kiersten White, Scott Peterson, Veronica Fish (Dessin)',
        'format'      => 'papier',
        'pages'       => 68,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'supernatural'],
        'cover_color' => 'genre-manga',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "What would you do for \$50,000? For Mack, the prize money would be life changing. She knows her time at the women's shelter is already up. And she's good at hiding. At least this time, her life doesn't depend on it–or so she thinks. The challenge is simple. All fourteen competitors must spend seven days hiding in an abandoned amusement park from dawn to dusk. There's only one rule: Don't get caught. But as the people around her begin disappearing one by one, Mack realizes this competition is more dangerous than she'd imagined, and that together might be the only way to survive.",
      ],
      [
        'id'          => 20,
        'title'       => 'Mauvais Souvenirs',
        'author'      => 'Morvan, Munuera (Dessin), Color Twins (Couleur)',
        'format'      => 'papier',
        'pages'       => 48,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Sir Pyle S. Culape',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "Sir Pyle, mythecin généraliste, continue à raconter ses souvenirs à son domestique, un spectre qu'il qualifie souvent de boulet (Pyle est un génie mais certes pas celui de l'humour). On retrouve des souvenirs de nos peurs ou émerveillements enfantins, toujours dévoyés : la sardine-garou, l'adultère de la Belle, la guérison du Père Fouettard, le Serpent sans Plumes... même le Manneken Pis, érigé au rang de mythe, n'échappe pas au sacrilège. Mais surtout on en apprend un peu plus sur Pyle lui-même grâce à une vieille connaissance, le père fouettard, mais surtout grâce à son frère et à son fils (car Pyle a un fils !). Voilà un tome à lire pour voir la vie d'une autre façon.",
      ],
      [
        'id'          => 21,
        'title'       => 'Rien ne se perd...',
        'author'      => 'Morvan, Munuera (Dessin), Color Twins (Couleur)',
        'format'      => 'papier',
        'pages'       => 48,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth'],
        'cover_color' => 'genre-manga',
        'series'      => 'Sir Pyle S. Culape',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "À l'allure d'éternel pubertaire, Sir Pyle vit à New York, dans un manoir reculé. Il est mythecin, le meilleur de sa profession ! Sa clientèle se constitue essentiellement de dieux et de monstres de légende… Et entre deux rendez-vous, il raconte ses mémoires à son spectre de domestique où il s'efforce toujours de se donner le beau rôle ...",
      ],
      [
        'id'          => 22,
        'title'       => 'Death Vigil, Vol. 1',
        'author'      => 'Stjepan Sejic',
        'format'      => 'papier',
        'pages'       => 284,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'supernatural', 'urban-fantasy'],
        'cover_color' => 'genre-manga',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Gifted? Join the Death Vigil in their ongoing war against the ever-growing power of the Primordial Enemy! Only catch is you have to die first. Become a corporeal immortal Death Knight and obtain reality-altering weaponry in the never-ending battle between good and evil.",
      ],
      [
        'id'          => 23,
        'title'       => 'Connais-toi toi-même',
        'author'      => 'Rutile, Zimra (Dessin)',
        'format'      => 'papier',
        'pages'       => 96,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth', 'mythology'],
        'cover_color' => 'genre-manga',
        'series'      => 'Mytho',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "Luka Asling a douze ans, et pour lui la vie c'est pas super marrant. Faut dire qu'il vit dans un monde où les dieux sont tombés sur la tête ! Enfin c'est une expression… En fait, ce sont les dieux qui gouvernent la vie des mortels. On pourrait penser qu'avec tant de pouvoirs et de sagesse, les dieux feraient de la vie sur terre un véritable paradis… Luka, lui, trouve au contraire le monde très imparfait, et il ne se prive pas de le dire ! Ce qui lui cause bien des soucis… Jusqu'au jour où on lui annonce qu'il est la réincarnation du dieu Loki et qu'il devra déclencher le Ragnarök… la fin du monde, quoi !",
      ],
      [
        'id'          => 24,
        'title'       => 'Deus ex machina',
        'author'      => 'Rutile, Zimra (Dessin)',
        'format'      => 'papier',
        'pages'       => 96,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth', 'mythology'],
        'cover_color' => 'genre-manga',
        'series'      => 'Mytho',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "Luka, alias Loki le destructeur des mondes, poursuit le recrutement de son équipe de choc pour préparer la fin des temps. Prochaine recrue : Arès, le dieu de la guerre, camouflé en la personne de Martial. D'après sa psy, ce petit garçon très timide serait en proie à de violents accès de colère. C'est à ce moment-là qu'il révèlerait son vrai visage... S'ils veulent compter sur le pouvoir du plus grand guerrier de tous les temps, Loki et Kâli n'ont pas le choix : ils vont devoir le pousser dans ses derniers retranchements. Déchaîne la fureur, Arès !",
      ],
      [
        'id'          => 25,
        'title'       => 'Les hors-la-loi',
        'author'      => 'Paul Jenkins, Humberto Ramos (Dessin)',
        'format'      => 'papier',
        'pages'       => 50,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth', 'fairy-tales'],
        'cover_color' => 'genre-manga',
        'series'      => 'Fairy Quest',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "Dans l'univers de Fairy Quest, le monde des fées et des contes pour enfants est huilé comme une horloge suisse. Tout est définitivement écrit, et il ne faut jamais sortir de l'histoire. Mais que se passe-t-il quand Le Petit Chapeau Rouge, épuisé(e) de réinterpréter chaque jour la même histoire, d'arpenter de façon répétitive la même route et le même chemin, de déclamer perpétuellement les mêmes discours, décide avec son complice le Loup de sortir des sentiers battus et de s'émanciper du scénario ? Et pourront-ils vraiment devenir libres, alors que l'infâme monsieur Grimm lance ses hommes de main à leurs trousses ?",
      ],
      [
        'id'          => 26,
        'title'       => 'Les parias',
        'author'      => 'Paul Jenkins, Humberto Ramos (Dessin)',
        'format'      => 'papier',
        'pages'       => 59,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth', 'fairy-tales'],
        'cover_color' => 'genre-manga',
        'series'      => 'Fairy Quest',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "Épuisé de réinterpréter chaque jour la même histoire que nous connaissons bien, le Petit Chaperon rouge a décidé de s'échapper ! En compagnie du Loup, ils ont décidé de fuir les griffes de l'infâme comte Grimm et de partir vivre dans un endroit où leur amitié ne serait pas interdite. Ils sont désormais hors-la-loi, en cavale, et perdu dans une forêt sombre et mystérieuse. Rien ne les avait préparés aux dangers qui les attendent... Sur la route, ils vont croiser Raiponce, des Trolls et bien d'autres étranges créatures.",
      ],
      [
        'id'          => 27,
        'title'       => 'Les parias',
        'author'      => 'Paul Jenkins, Humberto Ramos (Dessin)',
        'format'      => 'papier',
        'pages'       => 59,
        'duration'    => null,
        'genres'      => ['graphic-novel', 'fantasy', 'youth', 'fairy-tales'],
        'cover_color' => 'genre-manga',
        'series'      => 'Fairy Quest',
        'book_number' => 2,
        'language'    => 'fr',
        'summary'     => "Épuisé de réinterpréter chaque jour la même histoire que nous connaissons bien, le Petit Chaperon rouge a décidé de s'échapper ! En compagnie du Loup, ils ont décidé de fuir les griffes de l'infâme comte Grimm et de partir vivre dans un endroit où leur amitié ne serait pas interdite. Ils sont désormais hors-la-loi, en cavale, et perdu dans une forêt sombre et mystérieuse. Rien ne les avait préparés aux dangers qui les attendent... Sur la route, ils vont croiser Raiponce, des Trolls et bien d'autres étranges créatures.",
      ],
      [
        'id'          => 28,
        'title'       => "I've got your number",
        'author'      => 'Sophie Kinsella',
        'format'      => 'papier',
        'pages'       => 448,
        'duration'    => null,
        'genres'      => ['romance', 'contemporary', 'chick-lit'],
        'cover_color' => 'genre-romance',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Poppy Wyatt has never felt luckier. She is about to marry her ideal man, Magnus Tavish, but in one afternoon her \"happily ever after\" begins to fall apart. Not only has she lost her engagement ring in a hotel fire drill, but in the panic that follows, her phone is stolen. As she paces shakily around the lobby, she spots an abandoned phone in a trash can. Finders keepers! Now she can leave a number for the hotel to contact her when they find her ring. Perfect! Well, perfect except that the phone's owner, businessman Sam Roxton, doesn't agree. He wants his phone back and doesn't appreciate Poppy reading his messages and wading into his personal life. What ensues is a hilarious and unpredictable turn of events as Poppy and Sam increasingly upend each other's lives through emails and text messages. As Poppy juggles wedding preparations, mysterious phone calls, and hiding her left hand from Magnus and his parents, she soon realizes that she is in for the biggest surprise of her life.",
      ],
      [
        'id'          => 29,
        'title'       => 'Rosie change de vie',
        'author'      => 'Catherine Alliott',
        'format'      => 'papier',
        'pages'       => 447,
        'duration'    => null,
        'genres'      => ['romance', 'contemporary', 'chick-lit'],
        'cover_color' => 'genre-romance',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Ai-je eu tort d'épouser Harry ? Je n'avais jamais osé me poser la question. Mais, ce soir, le dîner chez les Boffington-Clarke a été encore plus barbant que d'habitude. Des gens si chics, qui passent leur temps à chasser la bécasse et à organiser des tournois de bridge... Bref, une soirée ennuyeuse à mourir. Bien entendu, Harry est rentré complètement saoul. Et, après avoir flirté ouvertement avec la baby-sitter, il s'est écroulé comme une masse. Trop, c'est trop ! J'ai su à cet instant que je ne pouvais plus supporter cet homme. Que mon mariage était terminé. J'allais divorcer.",
      ],
      [
        'id'          => 30,
        'title'       => 'The toy makers',
        'author'      => 'Robert Dinsdale',
        'format'      => 'papier',
        'pages'       => 468,
        'duration'    => null,
        'genres'      => ['fantasy', 'historical'],
        'cover_color' => 'genre-historical',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "The Emporium opens with the first sign of frost... It is 1917, and while war wages across Europe, in the heart of London, there is a place of hope and enchantment. The Emporium sells toys that capture the imagination of children and adults alike: patchwork dogs that seem alive, toy boxes that are bigger on the inside, soldiers that can fight battles on their own. Into this family business comes young Cathy Wray, running away from a shameful past. The Emporium takes her in, makes her one of its own. But Cathy is about to discover that the Emporium has secrets of its own...",
      ],
      [
        'id'          => 31,
        'title'       => 'Octopus: the Ocean\'s Intelligent Invertebrate',
        'author'      => 'Roland C. Anderson, Jennifer A. Mather, James B. Wood',
        'format'      => 'papier',
        'pages'       => 208,
        'duration'    => null,
        'genres'      => ['non-fiction', 'science'],
        'cover_color' => 'genre-non-fiction',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "The visually arresting and often misunderstood octopus has long captured popular imagination. With an alien appearance and an uncanny intellect, this exceptional sea creature has inspired fear in famous lore and legends. Yet its true nature is more wondrous still. After decades of research, the authors reveal a sensitive, curious, and playful animal with remarkable intelligence, an ability to defend itself with camouflage and jet propulsion, an intricate nervous system, and advanced problem-solving abilities.",
      ],
      [
        'id'          => 32,
        'title'       => 'Alien: La mécanique de la peur',
        'author'      => 'Roland C. Anderson, Jennifer A. Mather, James B. Wood',
        'format'      => 'papier',
        'pages'       => 208,
        'duration'    => null,
        'genres'      => ['non-fiction', 'science'],
        'cover_color' => 'genre-non-fiction',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "En 1979, dans la foulée du phénomène Star Wars, une étrange créature émerge de son oeuf emblématique. Sous les yeux des spectateurs apeurés, celui que l'on nommera ensuite xénomorphe repousse les limites de l'horreur et du corps humain dès sa première apparition. La science-fiction ne sera plus jamais la même. Au-delà de l'angoisse spatiale à laquelle elle est souvent rattachée, la saga Alien regorge de niveaux de lecture, métaphysiques ou psychanalytiques, à la richesse inattendue.",
      ],
      [
        'id'          => 33,
        'title'       => "L'échange",
        'author'      => 'Brenna Yovanoff',
        'format'      => 'papier',
        'pages'       => 331,
        'duration'    => null,
        'genres'      => ['supernatural', 'fantasy', 'youth'],
        'cover_color' => 'genre-fantastique',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Mackie Doyle donnerait n'importe quoi pour avoir une vie normale, jouer de la basse et passer du temps avec Tate Stewart, cette fille solitaire aux yeux noisette. Mais la petite ville de Gentry cache de sombres secrets. Il y a 16 ans, Mackie a été échangé contre un nouveau né : il est un 'remplaçant'. Il vient en fait d'un monde terrifiant où d'obscurs tunnels côtoient des eaux noires et pestilentielles... Lorsque le petit frère de Tate disparaît, Mackie n'a pas le choix : il doit affronter les créatures des entrailles de Gentry si il veut savoir à quel monde il appartient et sauver une vie innocente...",
      ],
      [
        'id'          => 34,
        'title'       => 'La dernière licorne',
        'author'      => 'Peter S. Beagle',
        'format'      => 'papier',
        'pages'       => 331,
        'duration'    => null,
        'genres'      => ['fantasy', 'youth'],
        'cover_color' => 'genre-fantasy',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "La dernière licorne vivait en toute quiétude, au bord du monde dans une forêt de lilas... jusqu'au jour où en espionnant la conversation de deux chasseurs, elle se rendit compte qu'elle était peut-être la dernière de sa race. Alors elle se mit en route. Sur les chemins du monde, elle rencontra un papillon occupé à chanter des chansons idiotes, fut enfermée dans une cage par des Tziganes heureux d'en faire une attraction fort lucrative, puis fit la connaissance de Schmendrick, un magicien sympathique et pour le moins incompétent.",
      ],
      [
        'id'          => 35,
        'title'       => 'NOS4A2',
        'author'      => 'Joe Hill',
        'format'      => 'papier',
        'pages'       => 331,
        'duration'    => null,
        'genres'      => ['horror', 'supernatural'],
        'cover_color' => 'genre-horreur',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Victoria McQueen has a secret gift for finding things: a misplaced bracelet, a missing photograph, answers to unanswerable questions. On her Raleigh Tuff Burner bike, she makes her way to a rickety covered bridge that, within moments, takes her wherever she needs to go, whether it's across Massachusetts or across the country. Charles Talent Manx has a way with children. He likes to take them for rides in his 1938 Rolls-Royce Wraith with the NOS4A2 vanity plate.",
      ],
      [
        'id'          => 36,
        'title'       => 'Une Princesse amoureuse',
        'author'      => 'Meg Cabot',
        'format'      => 'papier',
        'pages'       => 253,
        'duration'    => null,
        'genres'      => ['youth', 'romance'],
        'cover_color' => 'genre-jeunesse',
        'series'      => 'Journal d\'une princesse',
        'book_number' => 3,
        'language'    => 'fr',
        'summary'     => "Ce n'est déjà pas facile d'être lycéenne à New-York et princesse héritière de la principauté de Génovia. Mais voilà qu'en plus, Mia est amoureuse du frère de sa meilleure amie, Michael, qui ne semble pas du tout s'intéresser à elle. Que faire??? Se désespérer en cachette, faire semblant de s'intéresser à Kenny pour rendre Michael jaloux, renoncer ? Voyons, une Princesse ne renonce jamais !",
      ],
      [
        'id'          => 37,
        'title'       => 'For Whom The Belle Tolls',
        'author'      => 'Jaysea Lynn',
        'format'      => 'papier',
        'pages'       => 253,
        'duration'    => null,
        'genres'      => ['fantasy', 'romance'],
        'cover_color' => 'genre-fantasy',
        'series'      => "Hell's belles",
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "Lily is less than thrilled about her arrival to the Afterlife, but what awaits her is more fantastical than she ever could have imagined. Deities wait in line at the coffee shop. Fae flit between realms. Souls find ways to make death a beginning. As Lily explores everything the Afterlife has to offer, she finds herself drawn to a place most people would rather avoid at all costs: Hell.",
      ],
      [
        'id'          => 38,
        'title'       => 'Flic, sexy, démoniaque',
        'author'      => 'Ellie Cerane',
        'format'      => 'papier',
        'pages'       => 253,
        'duration'    => null,
        'genres'      => ['romance', 'urban-fantasy'],
        'cover_color' => 'genre-romance',
        'series'      => 'Nyx Chronicles',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "Camélia, démone quatre fois centenaire, agent secret, croqueuse d'hommes, se voit imposer un Ordinaire comme partenaire, grincheux et résistant à ses pouvoirs. Rajoutez à cela des disparitions qui s'accumulent et une enquête qui patine faute de témoins, saupoudrez le tout d'une attirance à laquelle son humain de flic refuse de céder, et vous obtiendrez un cocktail tout autant explosif qu'attractif !",
      ],
      [
        'id'          => 39,
        'title'       => 'God just wanted to play golf',
        'author'      => 'Craig W. Chenery',
        'format'      => 'papier',
        'pages'       => 310,
        'duration'    => null,
        'genres'      => ['horror', 'humour', 'fantasy'],
        'cover_color' => 'genre-humour',
        'series'      => 'The Oceanview Trilogy',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "God; omniscient creator, terrible golfer, and disgruntled CEO of Heaven, asks for little in life. He wants nothing more than for his private elevator to be repaired, ten minutes of peace and quiet to eat Girl Scout cookies, and an eighteen-hole round with the recently deceased British Prime Minister. So when a broken database causes his records department to send The Grim Reaper a list of souls not ready for reaping, his once peaceful life quickly begins to unravel.",
      ],
      [
        'id'          => 40,
        'title'       => 'Lucifer just wanted to pet kittens',
        'author'      => 'Craig W. Chenery',
        'format'      => 'papier',
        'pages'       => 392,
        'duration'    => null,
        'genres'      => ['horror', 'humour', 'fantasy'],
        'cover_color' => 'genre-humour',
        'series'      => 'The Oceanview Trilogy',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "LUCIFER: fallen angel, snappy dresser, and the dashingly good-looking CEO of Hell, enjoys a drama-free and peaceful life. He spends his days high-fiving new residents and ensuring their needs are met with an endless supply of LSD, electronic dance music, and neon glowsticks. So, when the entire population of Heaven shows up on his doorstep, his happy life is ripped out from beneath him.",
      ],
      [
        'id'          => 41,
        'title'       => 'Les yeux du dragon',
        'author'      => 'Stephen King',
        'format'      => 'papier',
        'pages'       => 253,
        'duration'    => null,
        'genres'      => ['fantasy', 'supernatural', 'youth'],
        'cover_color' => 'genre-fantasy',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "L'ombre de Flagg plane depuis quatre siècles sur le royaume de Delain... Le jour où la silhouette du sinistre magicien se glisse derrière le trône du roi Roland, c'est en vue d'accomplir son noir dessein : assurer le triomphe du mal. La machination se met en marche, vénéneuse comme le poison. Mais c'est compter sans une antique maison de poupée, quelques milliers de serviettes de table, les yeux d'un vieux dragon empaillé et, bien sûr, le courage de ceux qui refusent la tyrannie.",
      ],
      [
        'id'          => 42,
        'title'       => 'Blanche-Neige contre Merlin l\'enchanteur',
        'author'      => 'Catherine Dufour',
        'format'      => 'papier',
        'pages'       => 667,
        'duration'    => null,
        'genres'      => ['fantasy', 'supernatural', 'humour'],
        'cover_color' => 'genre-humour',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Tout le monde connaît Merlin. Tout le monde sait qu'il est amoureux de la Dame du Lac. Mais savez-vous que c'est un ange ? Qu'il est d'une beauté sans pareille ? Qu'il a une voix merveilleuse ? Et l'âme la plus noire qu'on puisse trouver, plus noire même que celle de Blanche Neige... Et savez-vous que c'est un vampire ? Un cycle foisonnant de trouvailles, en forme d'hommage à Terry Pratchett et aux Monty Python.",
      ],
      [
        'id'          => 43,
        'title'       => 'La mort me va si bien',
        'author'      => 'Louisa Méonis',
        'format'      => 'papier',
        'pages'       => 264,
        'duration'    => null,
        'genres'      => ['fantasy', 'bit-lit', 'humour'],
        'cover_color' => 'genre-humour',
        'series'      => 'Betty Angel',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "« Bon sang, je vais rester petite et boulotte pour l'éternité ! J'ai vraiment un karma de merde ! » Moi, c'est Betty. J'ai passé ma vie à jouer la bonne poire dont tout le monde profitait, pour finir noyée dans mes toilettes… Ma mort est aussi naze que l'était mon existence. Et comme si ça ne suffisait pas, je me retrouve catapultée dans une série d'épreuves terrifiantes pour devenir l'apprentie du bien trop sexy pour être honnête Ange de la Mort !",
      ],
      [
        'id'          => 44,
        'title'       => "Ella l'ensorcelée",
        'author'      => 'Gail Carson Levine',
        'format'      => 'papier',
        'pages'       => 264,
        'duration'    => null,
        'genres'      => ['fantasy', 'fairy-tales', 'youth'],
        'cover_color' => 'genre-jeunesse',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Le sort de la fée Lucinda est si puissant qu'Ella est obligée d'exécuter tous les ordres qu'on lui donne, quels qu'ils soient, même si elle s'y refuse de toutes ses forces. En grandissant, elle a appris à mettre toute son intelligence au service d'une lutte de chaque instant pour dissimuler sa vulnérabilité. Mais à présent que sa mère est morte, que son père a décidé de se remarier, la voilà plus fragile que jamais.",
      ],
      [
        'id'          => 45,
        'title'       => 'King Sorrow',
        'author'      => 'Joe Hill, narrated by a full cast',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '26h 04m',
        'genres'      => ['horror', 'supernatural', 'fantasy'],
        'cover_color' => 'genre-horreur',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Bookish college student Arthur Oakes and his friends summon the ancient dragon King Sorrow to escape local drug dealers forcing him into stealing rare books from Rackham College's library. Desperate to protect his imprisoned mother, Arthur turns to his close-knit group for a fantastical scheme that unleashes the dragon but binds them to a Faustian bargain requiring an annual human sacrifice or face death themselves.",
      ],
      [
        'id'          => 46,
        'title'       => 'Dungeon Crawler Carl',
        'author'      => 'Matt Dinniman, Sylvain Agaesse (narrateur)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '13h 31m',
        'genres'      => ['science-fiction', 'adventure', 'humour'],
        'cover_color' => 'genre-sf',
        'series'      => 'Dungeon Crawler Carl',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "Un homme. Le chat de son ex. Un jeu télévisé sadique où leur survie dépend de leur capacité à tuer avec style. En un éclair, chaque construction humaine érigée sur Terre s'effondre, créant un gigantesque donjon : un labyrinthe infernal de 18 niveaux remplis de pièges, de monstres et de butins. Seulement quelques survivants osent s'aventurer à l'intérieur, mais une fois que vous y pénétrez, impossible d'en ressortir.",
      ],
      [
        'id'          => 47,
        'title'       => 'Pride and Prejudice',
        'author'      => 'Jane Austen',
        'format'      => 'ebook',
        'pages'       => 384,
        'duration'    => null,
        'genres'      => ['romance', 'classic-literature', 'historical'],
        'cover_color' => 'genre-classique',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Élisabeth Bennet a quatre sœurs et une mère qui ne songe qu'à les marier. Quand parvient la nouvelle de l'installation à Netherfield, le domaine voisin, de Mr Bingley, célibataire et beau parti, toutes les dames des alentours sont en émoi, d'autant plus qu'il est accompagné de son ami Mr Darcy, un jeune et riche aristocrate.",
      ],
      [
        'id'          => 48,
        'title'       => 'Beaucoup de bruit pour rien',
        'author'      => 'William Shakespeare',
        'format'      => 'ebook',
        'pages'       => 342,
        'duration'    => null,
        'genres'      => ['theater', 'comedy', 'classic-literature', 'romance'],
        'cover_color' => 'genre-classique',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Après avoir triomphé de la guerre, le prince Don Pédro vient se reposer chez Léonato, gouverneur de Messine en Sicile. Le seigneur Claudio tombe amoureux d'Héro, fille de Léonato, pendant que le seigneur Bénédict, célibataire endurci, se chamaille avec la nièce du gouverneur, Béatrice. Much Ado About Nothing est une pièce toute en quiproquos, drôle, avec quelques bonnes réparties et des retournements dramatiques.",
      ],
      [
        'id'          => 49,
        'title'       => "Lignées de l'ombre – L'intégrale",
        'author'      => 'Roxane Dambre',
        'format'      => 'ebook',
        'pages'       => 776,
        'duration'    => null,
        'genres'      => ['romance', 'urban-fantasy', 'humour'],
        'cover_color' => 'genre-romance',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Moi qui pensais que mon plus grand défi cet été, ça serait d'aider le resto où je suis cheffe à décrocher une étoile, j'ai dû revoir très vite le sens de mes priorités ! Parce qu'en la recueillant, j'ai découvert que les fées ne sont pas les seuls êtres magiques qui existent. Les Chasseurs qui les traquent sont là, eux aussi.",
      ],
      [
        'id'          => 50,
        'title'       => 'A brazen curiosity',
        'author'      => 'Lynn Messina, Jill Smith (narrator)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '07h 29m',
        'genres'      => ['mystery', 'romance', 'historical', 'cozy-mystery'],
        'cover_color' => 'genre-mystery',
        'series'      => 'Beatrice Hyde-Clare mysteries',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "At the decrepit old age of six-and-twenty, Miss Beatrice Hyde-Clare has virtually no hope of landing a husband. An orphan living off her relatives' charity, her job is to sit with her needlework and to keep her thoughts to herself. When Bea receives an invitation to an elegant country party, she intends to do just that. But, when she stumbles upon the dead body of another houseguest, all Bea's good intentions fly out the well-appointed window.",
      ],
      [
        'id'          => 51,
        'title'       => 'Swordheart',
        'author'      => 'T. Kingfisher, Jesse Vilinsky (Narrator)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '14h32m',
        'genres'      => ['fantasy', 'romance', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => 'Swordheart',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "Halla is a housekeeper who has suddenly inherited her great-uncle's estate... and, unfortunately, his relatives. Sarkis is an immortal swordsman trapped in a prison of enchanted steel. When Halla draws the sword that imprisons him, Sarkis finds himself attempting to defend his new wielder against everything from bandits and roving inquisitors to her own in-laws.",
      ],
      [
        'id'          => 52,
        'title'       => 'Snake-Eater',
        'author'      => 'T. Kingfisher, Elena Ray (Narrator)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '10h56',
        'genres'      => ['fantasy', 'horror', 'mythology', 'humour'],
        'cover_color' => 'genre-horreur',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "With only a few dollars to her name and her beloved dog Copper by her side, Selena flees her past in the city to claim her late aunt's house in the desert town of Quartz Creek. The scorpions and spiders are better than what she left behind. But something lurks beneath the surface. Like the desert gods and spirits lingering outside Selena's house at night, keeping watch.",
      ],
      [
        'id'          => 53,
        'title'       => 'Throne in the dark',
        'author'      => 'A.K Caggiano, Ellen Quay (Narrator), Seth Podowitz (Narrator)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '14h13m',
        'genres'      => ['fantasy', 'romance', 'humour'],
        'cover_color' => 'genre-fantasy',
        'series'      => 'Villains and Virtues',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "Dark lord, demon spawn, prophesied realm destroyer. With a demon for a father, Damien Maleficus Bloodthorne's destiny could be nothing but nefarious. And then, her: bubbly, obnoxious, blonde. A tiny yet troublesome thief calling herself Amma completely upsets Damien's malevolent plans when she mistakenly gets chained to his side through magic, forcing him to drag her across the realm.",
      ],
      [
        'id'          => 54,
        'title'       => "Harry Potter et le prisonnier d'Azkaban",
        'author'      => 'J.K. Rowling, Bernard Giraudeau (Narrateur)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '11h36m',
        'genres'      => ['fantasy', 'youth', 'magie'],
        'cover_color' => 'genre-jeunesse',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Troisième année à Poudlard pour Harry Potter, Ron et Hermione. Alors que le trio s'apprête à vivre une année scolaire mouvementée, une nouvelle menace plane sur le monde des sorciers : Sirius Black, un dangereux criminel, s'est échappé de la prison d'Azkaban et semble déterminé à retrouver Harry.",
      ],
      [
        'id'          => 55,
        'title'       => 'Vicious',
        'author'      => 'V.E. Schwab, Jeremy Arthur (Narrator)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '09h24m',
        'genres'      => ['science-fiction', 'fantasy', 'thriller'],
        'cover_color' => 'genre-sf',
        'series'      => 'Villains',
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "Victor and Eli started out as college roommates—brilliant, arrogant, lonely boys who recognized the same sharpness and ambition in each other. In their senior year, a shared research interest in adrenaline, near-death experiences, and seemingly supernatural events reveals an intriguing possibility: that under the right conditions, someone could develop extraordinary abilities. But when their thesis moves from the academic to the experimental, things go horribly wrong.",
      ],
      [
        'id'          => 56,
        'title'       => 'Vengeful',
        'author'      => 'V.E. Schwab, Jeremy Arthur (Narrator)',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '09h24m',
        'genres'      => ['science-fiction', 'fantasy'],
        'cover_color' => 'genre-sf',
        'series'      => 'Villains',
        'book_number' => 2,
        'language'    => 'en',
        'summary'     => "Magneto and Professor X. Superman and Lex Luthor. Victor Vale and Eli Ever. Great partnerships, now soured on the vine. But Marcella Riggins needs no one. Flush from her brush with death, she's finally gained the control she's always sought - and will use her newfound power to bring the city of Merit to its knees.",
      ],
      [
        'id'          => 57,
        'title'       => 'Good Neighbors - The Full Collection',
        'author'      => 'Stephanie Burgis',
        'format'      => 'ebook',
        'pages'       => 202,
        'duration'    => null,
        'genres'      => ['fantasy', 'short-story', 'humour', 'steampunk'],
        'cover_color' => 'genre-fantasy',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Mia Brandt knows better than to ever again allow her true powers to be discovered. Ever since her last neighbors burned down her workshop in a night of terror and flame, she's been determined to stay solitary, safe, and - to all outside appearances - perfectly respectable... But Leander Fabian, whose sinister castle looms over her cozy new cottage, has far more dangerous ideas in mind.",
      ],
      [
        'id'          => 58,
        'title'       => 'Bury your gays',
        'author'      => 'Chuck Tingle',
        'format'      => 'ebook',
        'pages'       => null,
        'duration'    => null,
        'genres'      => ['science-fiction', 'horror'],
        'cover_color' => 'genre-sf',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Misha knows that chasing success in Hollywood can be hell. But finally, after years of trying to make it, his big moment is here: an Oscar nomination. And the executives at the studio for his long-running streaming series know just the thing to kick his career to the next level: kill off the gay characters, 'for the algorithm' in the upcoming season finale. Misha refuses, but he soon realizes that he's just put a target on his back.",
      ],
      [
        'id'          => 59,
        'title'       => 'The Sun Down Motel',
        'author'      => 'Simone St. James',
        'format'      => 'ebook',
        'pages'       => 327,
        'duration'    => null,
        'genres'      => ['thriller', 'horror', 'mystery'],
        'cover_color' => 'genre-thriller',
        'series'      => null,
        'book_number' => null,
        'language'    => 'en',
        'summary'     => "Upstate New York, 1982. Viv Delaney wants to move to New York City, and to help pay for it she takes a job as the night clerk at the Sun Down Motel in Fell, New York. But something isn't right at the motel, something haunting and scary. Upstate New York, 2017. Carly Kirk has never been able to let go of the story of her aunt Viv, who mysteriously disappeared from the Sun Down before she was born.",
      ],
      [
        'id'          => 60,
        'title'       => 'Loup, y es-tu ?',
        'author'      => 'Aurore Aylin',
        'format'      => 'ebook',
        'pages'       => 609,
        'duration'    => null,
        'genres'      => ['romance', 'urban-fantasy', 'mystery'],
        'cover_color' => 'genre-romance',
        'series'      => 'Nielsen Investigations',
        'book_number' => 1,
        'language'    => 'fr',
        'summary'     => "Croiser un monstre une nuit de pleine lune ? Elle s'en serait bien passé ! Engagée comme secrétaire par l'agence de détectives Nielsen Investigations après avoir perdu son emploi dans des circonstances rocambolesques, Enora est loin de s'attendre à voir sa vie basculer. Il faut dire qu'elle ignore un détail insignifiant sur ses nouveaux patrons : ce sont des métamorphes !",
      ],
      [
        'id'          => 61,
        'title'       => 'Ivy Wilde - Intégrale',
        'author'      => 'Helen Harper',
        'format'      => 'ebook',
        'pages'       => 816,
        'duration'    => null,
        'genres'      => ['romance', 'urban-fantasy', 'magical-realism', 'humour'],
        'cover_color' => 'genre-romance',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Bon, soyons clairs : Ivy Wilde n'est pas une héroïne. C'est même la dernière personne que vous contacteriez si vous aviez besoin d'une aide magique, malgré ses talents. Si ça ne tenait qu'à elle, Ivy passerait ses journées affalée dans le canapé, devant la télé, paquets de chips en main, à papoter avec son familier félin jusqu'à ce que mort s'en suive.",
      ],
      [
        'id'          => 62,
        'title'       => 'Echiquier du Mal - Intégrale',
        'author'      => 'Dan Simmons',
        'format'      => 'ebook',
        'pages'       => 1200,
        'duration'    => null,
        'genres'      => ['thriller', 'science-fiction', 'fantastique'],
        'cover_color' => 'genre-thriller',
        'series'      => null,
        'book_number' => null,
        'language'    => 'fr',
        'summary'     => "Ils ont le talent. Ils ont la capacité de pénétrer mentalement dans notre esprit pour nous transformer en marionnettes au service de leurs perversions et de leur appétit de pouvoir. Ils tirent les ficelles de l'Histoire. Sans eux le nazisme n'aurait peut-être pas été cette monstruosité dont nous avons du mal à nous remettre.",
      ],
      [
        'id'          => 63,
        'title'       => 'Mythos',
        'author'      => 'Stephen Fry',
        'format'      => 'audio',
        'pages'       => null,
        'duration'    => '15h26m',
        'genres'      => ['mythology', 'humour'],
        'cover_color' => 'genre-humour',
        'series'      => "Stephen Fry's Greek Myths",
        'book_number' => 1,
        'language'    => 'en',
        'summary'     => "Mythos is a modern collection of Greek myths, stylishly retold by legendary writer, actor, and comedian Stephen Fry. Fry transforms the adventures of Zeus and the Olympians into emotionally resonant and deeply funny stories, without losing any of their original wonder.",
      ],
    ];
  }
}
